bids_dir: '/home/ROBARTS/ataha/graham/scratch/afids-data/data/datasets/AFIDs-HCP'
output_dir: '/home/ROBARTS/ataha/graham/scratch/afids-data/data/datasets/AFIDs-HCP/derivatives'
template: '/home/ROBARTS/ataha/graham/scratch/afids_auto_preproc/resources/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz'
synthstrip: '/home/ROBARTS/ataha/graham/scratch/afids_auto_preproc/resources/synthstrip.1.3.sif'
            
  
pybids_inputs:
  t1w:
    filters:
      suffix: T1w
      extension: .nii.gz
      datatype: anat
    wildcards:
    - subject
    - session
    - acquisition
    - task
    
singularity:
  synthstrip: /home/ROBARTS/ataha/graham/scratch/synthstrip.1.3.sif
